# Generated by Django 3.2.9 on 2021-12-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='short_descr',
            field=models.TextField(default='', max_length=150, verbose_name='краткое описание'),
        ),
    ]
