# Generated by Django 3.2.9 on 2022-02-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0004_auto_20220208_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.CharField(blank=True, max_length=32, verbose_name="тэг"),
        ),
    ]
