# Generated by Django 3.2.9 on 2021-12-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debiuser",
            name="age",
            field=models.PositiveIntegerField(null=True, verbose_name="возраст"),
        ),
        migrations.AddField(
            model_name="debiuser",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="avatars"),
        ),
    ]
