# Generated by Django 3.2.9 on 2022-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_alter_debiuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debiuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
