# Generated by Django 3.2.9 on 2022-01-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0006_debiuserprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="debiuser",
            name="avatar",
        ),
        migrations.AddField(
            model_name="debiuserprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to="avatars", verbose_name="аватарка"
            ),
        ),
    ]
