# Generated by Django 3.2.9 on 2022-02-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0010_alter_debiuserprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debiuser",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="активный/приостановлен"
            ),
        ),
    ]
